apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: gost-on
data:
  PYTHONUNBUFFERED: "1"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: gost-on
data:
  nginx.conf: |
    # содержимое вашего nginx.conf файла
      worker_processes 1;

      events {
          worker_connections 1024;
      }

      http {
          upstream app {
                server app:5000;
          }

          server {
              listen 80;
              server_name localhost;

              location / {
                  proxy_pass http://app;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              }

              location /static/ {
                  proxy_pass http://app/static/;
                  proxy_set_header Host \$host;
                  expires 1d;
                  add_header Cache-Control "public";
              }
          }
      }
---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: gost-on
stringData:
  POSTGRES_USER: "appuser"
  POSTGRES_PASSWORD: "apppass"
  POSTGRES_DB: "appdb"

---

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: gost-on
stringData:
    DATABASE_URL: "postgresql://appuser:apppass@postgres:5432/appdb" 