apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: gost-on
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: postgres-user
      containers:
      - name: postgres
        image: postgres:17-alpine
        envFrom:
        - secretRef:
            name: postgres-secrets
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "700Mi"
            cpu: "150m"
          limits:
            memory: "1200Mi"
            cpu: "300m"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: gost-on
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: gost-on
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-user
  namespace: gost-on
