apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
stringData:
  MYSQL_DATABASE: exampledb
  MYSQL_USER: exampleuser
  MYSQL_PASSWORD: examplepass
  MYSQL_RANDOM_ROOT_PASSWORD: '1'

---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
stringData:
  WORDPRESS_DB_HOST: mysql
  WORDPRESS_DB_USER: exampleuser
  WORDPRESS_DB_PASSWORD: examplepass
  WORDPRESS_DB_NAME: exampledb
  